### ISSUE TITLE
It does not create a volume directory

### ISSUE THREAD

**Issue by Example0365** [skyportlabs/skyportd#18]
node:internal/fs/promises:948
  const result = await PromisePrototypeThen(
                 ^

Error: ENOENT: no such file or directory, scandir '/etc/skyportd/volumes'
    at async Object.readdir (node:internal/fs/promises:948:18)
    at async getDirectories (/etc/skyportd/routes/FTP.js:19:17)
    at async initializeUsers (/etc/skyportd/routes/FTP.js:81:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/etc/skyportd/volumes'
}

**Comment by Example0365** [comment]
just do mkdir volumes to fix the issue
